### PR TITLE
Fix pagination issues in the user management component

### LINKED ISSUE #819: `ngb-pagination` issues - User Management Component

### PR DESCRIPTION
**Pull request by matthew-morris-cessda**
This closes #819

### CODE REVIEW

**Review by pakoselo — COMMENTED** [review]
The editor search is not working: https://vocabularies-dev.cessda.eu/editor

ERROR TypeError: Cannot read properties of undefined (reading 'forEach')
    at VocabularyUtil.sortLangByEnum (vocabulary-util.ts:298:15)
    at VocabularySearchResultComponent.sortLangByEnum (vocabulary-search-result.component.ts:394:12)
    at VocabularySearchResultComponent_ng_template_85_div_3_Template (vocabulary-search-result.component.html:187:62)
    at executeTemplate (core.js:9705:1)
    at refreshView (core.js:9571:1)
    at refreshEmbeddedViews (core.js:10696:1)
    at refreshView (core.js:9595:1)
    at refreshEmbeddedViews (core.js:10696:1)
    at refreshView (core.js:9595:1)
    at refreshComponent (core.js:10742:1)

**Comment by matthew-morris-cessda** [comment]
The editor search has been fixed

**Review by pakoselo — COMMENTED** [review]
The search in editor is working, but not searching over right vocabularies. It should work over DRAFT/READY_TO_TRANSLATE/READY_TO_PUBLISH versions too. It works only over published ones. Another thing is that, the facet field status in the Editor search isn't working at all.

**Comment by matthew-morris-cessda** [comment]
Fixed, this was caused by the HTTP request being sent out in the constructor rather than `ngOnInit()`

**Review by pakoselo — APPROVED** [review]

**Comment by matthew-morris-cessda** [comment]
Thanks Martin for looking at this and finding the bugs

**Pull request merged**
